[2024-01-29T10:01:38.998+0000] {taskinstance.py:1946} INFO - Dependencies not met for <TaskInstance: manage_data_lake_dag.spark_job_formatted manual__2024-01-29T09:31:26.429792+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2024-01-29T10:01:38.998352+00:00 and task will be retried at 2024-01-29T10:06:35.024743+00:00.
[2024-01-29T10:01:39.003+0000] {local_task_job_runner.py:160} INFO - Task is not able to be run
[2024-01-29T10:09:40.755+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: manage_data_lake_dag.spark_job_formatted manual__2024-01-29T09:31:26.429792+00:00 [queued]>
[2024-01-29T10:09:40.766+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: manage_data_lake_dag.spark_job_formatted manual__2024-01-29T09:31:26.429792+00:00 [queued]>
[2024-01-29T10:09:40.766+0000] {taskinstance.py:2170} INFO - Starting attempt 3 of 6
[2024-01-29T10:09:40.782+0000] {taskinstance.py:2191} INFO - Executing <Task(SparkSubmitOperator): spark_job_formatted> on 2024-01-29 09:31:26.429792+00:00
[2024-01-29T10:09:40.788+0000] {standard_task_runner.py:60} INFO - Started process 85443 to run task
[2024-01-29T10:09:40.799+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'manage_data_lake_dag', 'spark_job_formatted', 'manual__2024-01-29T09:31:26.429792+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/data_lake_dag.py', '--cfg-path', '/tmp/tmp4lrfjcci']
[2024-01-29T10:09:40.802+0000] {standard_task_runner.py:88} INFO - Job 89: Subtask spark_job_formatted
[2024-01-29T10:09:40.849+0000] {task_command.py:423} INFO - Running <TaskInstance: manage_data_lake_dag.spark_job_formatted manual__2024-01-29T09:31:26.429792+00:00 [running]> on host instance-1.europe-west9-a.c.data-lake-project-409321.internal
[2024-01-29T10:09:40.926+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='juniortemgoua0' AIRFLOW_CTX_DAG_ID='manage_data_lake_dag' AIRFLOW_CTX_TASK_ID='spark_job_formatted' AIRFLOW_CTX_EXECUTION_DATE='2024-01-29T09:31:26.429792+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-29T09:31:26.429792+00:00'
[2024-01-29T10:09:40.934+0000] {base.py:83} INFO - Using connection ID 'spark_default' for task execution.
[2024-01-29T10:09:40.936+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master yarn --conf spark.hadoop.yarn.resourcemanager.hostname=resourcemanager.fqdn --conf spark.hadoop.yarn.resourcemanager.address=resourcemanager.fqdn:8032 --name arrow-spark --class RawToFormatted --queue root.default --deploy-mode client /home/juniortemgoua0/DataLake/jobs/processes/scala/spark_process/target/scala-2.12/spark_job_2.12-0.1.0.jar gs://data-lake-buck
[2024-01-29T10:09:43.544+0000] {spark_submit.py:571} INFO - 24/01/29 10:09:43 INFO SparkContext: Running Spark version 3.5.0
[2024-01-29T10:09:43.549+0000] {spark_submit.py:571} INFO - 24/01/29 10:09:43 INFO SparkContext: OS info Linux, 5.15.0-1049-gcp, amd64
[2024-01-29T10:09:43.550+0000] {spark_submit.py:571} INFO - 24/01/29 10:09:43 INFO SparkContext: Java version 17.0.9
[2024-01-29T10:09:43.700+0000] {spark_submit.py:571} INFO - 24/01/29 10:09:43 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-01-29T10:09:43.869+0000] {spark_submit.py:571} INFO - 24/01/29 10:09:43 INFO ResourceUtils: ==============================================================
[2024-01-29T10:09:43.871+0000] {spark_submit.py:571} INFO - 24/01/29 10:09:43 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-01-29T10:09:43.872+0000] {spark_submit.py:571} INFO - 24/01/29 10:09:43 INFO ResourceUtils: ==============================================================
[2024-01-29T10:09:43.873+0000] {spark_submit.py:571} INFO - 24/01/29 10:09:43 INFO SparkContext: Submitted application: RawToFormatted
[2024-01-29T10:09:43.914+0000] {spark_submit.py:571} INFO - 24/01/29 10:09:43 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-01-29T10:09:43.928+0000] {spark_submit.py:571} INFO - 24/01/29 10:09:43 INFO ResourceProfile: Limiting resource is cpus at 1 tasks per executor
[2024-01-29T10:09:43.930+0000] {spark_submit.py:571} INFO - 24/01/29 10:09:43 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-01-29T10:09:44.013+0000] {spark_submit.py:571} INFO - 24/01/29 10:09:44 INFO SecurityManager: Changing view acls to: juniortemgoua0
[2024-01-29T10:09:44.013+0000] {spark_submit.py:571} INFO - 24/01/29 10:09:44 INFO SecurityManager: Changing modify acls to: juniortemgoua0
[2024-01-29T10:09:44.014+0000] {spark_submit.py:571} INFO - 24/01/29 10:09:44 INFO SecurityManager: Changing view acls groups to:
[2024-01-29T10:09:44.015+0000] {spark_submit.py:571} INFO - 24/01/29 10:09:44 INFO SecurityManager: Changing modify acls groups to:
[2024-01-29T10:09:44.016+0000] {spark_submit.py:571} INFO - 24/01/29 10:09:44 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: juniortemgoua0; groups with view permissions: EMPTY; users with modify permissions: juniortemgoua0; groups with modify permissions: EMPTY
[2024-01-29T10:09:44.367+0000] {spark_submit.py:571} INFO - 24/01/29 10:09:44 INFO Utils: Successfully started service 'sparkDriver' on port 44185.
[2024-01-29T10:09:44.409+0000] {spark_submit.py:571} INFO - 24/01/29 10:09:44 INFO SparkEnv: Registering MapOutputTracker
[2024-01-29T10:09:44.465+0000] {spark_submit.py:571} INFO - 24/01/29 10:09:44 INFO SparkEnv: Registering BlockManagerMaster
[2024-01-29T10:09:44.488+0000] {spark_submit.py:571} INFO - 24/01/29 10:09:44 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-01-29T10:09:44.489+0000] {spark_submit.py:571} INFO - 24/01/29 10:09:44 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-01-29T10:09:44.540+0000] {spark_submit.py:571} INFO - 24/01/29 10:09:44 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-01-29T10:09:44.566+0000] {spark_submit.py:571} INFO - 24/01/29 10:09:44 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-37c6f3cd-172c-43f5-9d30-8096b90cdc1b
[2024-01-29T10:09:44.586+0000] {spark_submit.py:571} INFO - 24/01/29 10:09:44 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-01-29T10:09:44.661+0000] {spark_submit.py:571} INFO - 24/01/29 10:09:44 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-01-29T10:09:44.851+0000] {spark_submit.py:571} INFO - 24/01/29 10:09:44 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2024-01-29T10:09:44.979+0000] {spark_submit.py:571} INFO - 24/01/29 10:09:44 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2024-01-29T10:09:45.030+0000] {spark_submit.py:571} INFO - 24/01/29 10:09:45 INFO SparkContext: Added JAR file:/home/juniortemgoua0/DataLake/jobs/processes/scala/spark_process/target/scala-2.12/spark_job_2.12-0.1.0.jar at spark://instance-1.europe-west9-a.c.data-lake-project-409321.internal:44185/jars/spark_job_2.12-0.1.0.jar with timestamp 1706522983528
[2024-01-29T10:09:45.310+0000] {spark_submit.py:571} INFO - 24/01/29 10:09:45 INFO DefaultNoHARMFailoverProxyProvider: Connecting to ResourceManager at resourcemanager.fqdn/<unresolved>:8032
[2024-01-29T10:09:46.518+0000] {spark_submit.py:571} INFO - 24/01/29 10:09:46 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 0 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:09:47.519+0000] {spark_submit.py:571} INFO - 24/01/29 10:09:47 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 1 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:09:48.522+0000] {spark_submit.py:571} INFO - 24/01/29 10:09:48 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 2 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:09:49.523+0000] {spark_submit.py:571} INFO - 24/01/29 10:09:49 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 3 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:09:50.524+0000] {spark_submit.py:571} INFO - 24/01/29 10:09:50 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 4 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:09:51.524+0000] {spark_submit.py:571} INFO - 24/01/29 10:09:51 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 5 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:09:52.525+0000] {spark_submit.py:571} INFO - 24/01/29 10:09:52 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 6 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:09:53.529+0000] {spark_submit.py:571} INFO - 24/01/29 10:09:53 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 7 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:09:54.529+0000] {spark_submit.py:571} INFO - 24/01/29 10:09:54 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 8 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:09:55.530+0000] {spark_submit.py:571} INFO - 24/01/29 10:09:55 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 9 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:09:56.552+0000] {spark_submit.py:571} INFO - 24/01/29 10:09:56 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 0 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:09:57.553+0000] {spark_submit.py:571} INFO - 24/01/29 10:09:57 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 1 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:09:58.557+0000] {spark_submit.py:571} INFO - 24/01/29 10:09:58 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 2 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:09:59.558+0000] {spark_submit.py:571} INFO - 24/01/29 10:09:59 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 3 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:10:00.558+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:00 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 4 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:10:01.559+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:01 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 5 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:10:02.559+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:02 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 6 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:10:03.563+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:03 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 7 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:10:04.564+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:04 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 8 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:10:05.565+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:05 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 9 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:10:05.578+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:05 INFO RetryInvocationHandler: java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException: Invalid host name: local host is: "instance-1/10.200.0.5"; destination host is: "resourcemanager.fqdn":8032; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost; For more details see:  http://wiki.apache.org/hadoop/UnknownHost, while invoking ApplicationClientProtocolPBClientImpl.getNewApplication over null after 1 failover attempts. Trying to failover after sleeping for 16650ms.
[2024-01-29T10:10:23.255+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:23 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 0 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:10:24.256+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:24 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 1 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:10:25.256+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:25 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 2 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:10:26.257+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:26 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 3 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:10:27.257+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:27 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 4 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:10:28.263+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:28 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 5 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:10:29.264+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:29 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 6 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:10:30.264+0000] {spark_submit.py:571} INFO - 24/01/29 10:10:30 INFO Client: Retrying connect to server: resourcemanager.fqdn/<unresolved>:8032. Already tried 7 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
[2024-01-29T10:10:31.172+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-01-29T10:10:31.177+0000] {process_utils.py:131} INFO - Sending Signals.SIGTERM to group 85443. PIDs of all processes in the group: [85444, 85443]
[2024-01-29T10:10:31.177+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 85443
[2024-01-29T10:10:31.178+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-01-29T10:10:31.178+0000] {spark_submit.py:697} INFO - Sending kill signal to spark-submit
[2024-01-29T10:10:31.351+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=85443, status='terminated', exitcode=0, started='10:09:40') (85443) terminated with exit code 0
[2024-01-29T10:10:31.351+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=85444, status='terminated', started='10:09:40') (85444) terminated with exit code None
