[2024-01-30T18:31:00.052+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: manage_data_lake_dag.dataproc_job_raw_to_formatted scheduled__2024-01-14T00:00:00+00:00 [queued]>
[2024-01-30T18:31:00.059+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: manage_data_lake_dag.dataproc_job_raw_to_formatted scheduled__2024-01-14T00:00:00+00:00 [queued]>
[2024-01-30T18:31:00.059+0000] {taskinstance.py:2170} INFO - Starting attempt 4 of 6
[2024-01-30T18:31:00.075+0000] {taskinstance.py:2191} INFO - Executing <Task(DataprocSubmitJobOperator): dataproc_job_raw_to_formatted> on 2024-01-14 00:00:00+00:00
[2024-01-30T18:31:00.081+0000] {standard_task_runner.py:60} INFO - Started process 74052 to run task
[2024-01-30T18:31:00.088+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'manage_data_lake_dag', 'dataproc_job_raw_to_formatted', 'scheduled__2024-01-14T00:00:00+00:00', '--job-id', '361', '--raw', '--subdir', 'DAGS_FOLDER/data_lake_dag.py', '--cfg-path', '/tmp/tmp7_m7a3wr']
[2024-01-30T18:31:00.090+0000] {standard_task_runner.py:88} INFO - Job 361: Subtask dataproc_job_raw_to_formatted
[2024-01-30T18:31:00.140+0000] {task_command.py:423} INFO - Running <TaskInstance: manage_data_lake_dag.dataproc_job_raw_to_formatted scheduled__2024-01-14T00:00:00+00:00 [running]> on host instance-1.europe-west9-a.c.data-lake-project-409321.internal
[2024-01-30T18:31:00.213+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='juniortemgoua0' AIRFLOW_CTX_DAG_ID='manage_data_lake_dag' AIRFLOW_CTX_TASK_ID='dataproc_job_raw_to_formatted' AIRFLOW_CTX_EXECUTION_DATE='2024-01-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-14T00:00:00+00:00'
[2024-01-30T18:31:00.215+0000] {dataproc.py:2317} INFO - Submitting job
[2024-01-30T18:31:00.220+0000] {connection.py:234} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-30T18:31:00.226+0000] {base.py:83} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-01-30T18:31:00.402+0000] {dataproc.py:2329} INFO - Job a501dcd0-d8fb-4a94-a345-2017e7a8fe72 submitted successfully.
[2024-01-30T18:31:00.414+0000] {dataproc.py:2363} INFO - Waiting for job a501dcd0-d8fb-4a94-a345-2017e7a8fe72 to complete
[2024-01-30T18:33:11.394+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/juniortemgoua0/DataLake/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/juniortemgoua0/DataLake/venv/lib/python3.8/site-packages/airflow/providers/google/cloud/operators/dataproc.py", line 2364, in execute
    self.hook.wait_for_job(
  File "/home/juniortemgoua0/DataLake/venv/lib/python3.8/site-packages/airflow/providers/google/common/hooks/base_google.py", line 482, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/juniortemgoua0/DataLake/venv/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/dataproc.py", line 740, in wait_for_job
    raise AirflowException(f"Job failed:\n{job}")
airflow.exceptions.AirflowException: Job failed:
reference {
  project_id: "data-lake-project-409321"
  job_id: "a501dcd0-d8fb-4a94-a345-2017e7a8fe72"
}
placement {
  cluster_name: "cluster-f499"
  cluster_uuid: "13fc8c1e-24fd-4462-8a44-4c3a49636ea2"
}
spark_job {
  main_class: "RawToFormatted"
  args: "gs://data-lake-buck"
  args: "dataproc"
  jar_file_uris: "gs://data-lake-buck/spark_job_2.12-0.1.0.jar"
  properties {
    key: "spark.airflow.execution_date"
    value: "2024-01-14"
  }
}
status {
  state: ERROR
  details: "Job failed with message [Exception in thread \"main\" org.apache.spark.sql.AnalysisException: Path does not exist: gs://data-lake-buck/raw/football_data/teams/2024-01-14.json]. Additional details can be found at:\nhttps://console.cloud.google.com/dataproc/jobs/a501dcd0-d8fb-4a94-a345-2017e7a8fe72?project=data-lake-project-409321&region=europe-west9\ngcloud dataproc jobs wait \'a501dcd0-d8fb-4a94-a345-2017e7a8fe72\' --region \'europe-west9\' --project \'data-lake-project-409321\'\nhttps://console.cloud.google.com/storage/browser/dataproc-staging-europe-west9-58760042001-uborul6i/google-cloud-dataproc-metainfo/13fc8c1e-24fd-4462-8a44-4c3a49636ea2/jobs/a501dcd0-d8fb-4a94-a345-2017e7a8fe72/\ngs://dataproc-staging-europe-west9-58760042001-uborul6i/google-cloud-dataproc-metainfo/13fc8c1e-24fd-4462-8a44-4c3a49636ea2/jobs/a501dcd0-d8fb-4a94-a345-2017e7a8fe72/driveroutput.*"
  state_start_time {
    seconds: 1706639585
    nanos: 868634000
  }
}
status_history {
  state: PENDING
  state_start_time {
    seconds: 1706639460
    nanos: 386118000
  }
}
status_history {
  state: SETUP_DONE
  state_start_time {
    seconds: 1706639460
    nanos: 439315000
  }
}
status_history {
  state: RUNNING
  state_start_time {
    seconds: 1706639460
    nanos: 681588000
  }
}
yarn_applications {
  name: "RawToFormatted"
  state: FINISHED
  progress: 1
  tracking_url: "http://cluster-f499-m.europe-west9-c.c.data-lake-project-409321.internal.:8088/proxy/application_1706622505355_0107/"
}
driver_output_resource_uri: "gs://dataproc-staging-europe-west9-58760042001-uborul6i/google-cloud-dataproc-metainfo/13fc8c1e-24fd-4462-8a44-4c3a49636ea2/jobs/a501dcd0-d8fb-4a94-a345-2017e7a8fe72/driveroutput"
driver_control_files_uri: "gs://dataproc-staging-europe-west9-58760042001-uborul6i/google-cloud-dataproc-metainfo/13fc8c1e-24fd-4462-8a44-4c3a49636ea2/jobs/a501dcd0-d8fb-4a94-a345-2017e7a8fe72/"
job_uuid: "a501dcd0-d8fb-4a94-a345-2017e7a8fe72"
done: true

[2024-01-30T18:33:11.398+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=manage_data_lake_dag, task_id=dataproc_job_raw_to_formatted, execution_date=20240114T000000, start_date=20240130T183100, end_date=20240130T183311
[2024-01-30T18:33:11.411+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 361 for task dataproc_job_raw_to_formatted (Job failed:
reference {
  project_id: "data-lake-project-409321"
  job_id: "a501dcd0-d8fb-4a94-a345-2017e7a8fe72"
}
placement {
  cluster_name: "cluster-f499"
  cluster_uuid: "13fc8c1e-24fd-4462-8a44-4c3a49636ea2"
}
spark_job {
  main_class: "RawToFormatted"
  args: "gs://data-lake-buck"
  args: "dataproc"
  jar_file_uris: "gs://data-lake-buck/spark_job_2.12-0.1.0.jar"
  properties {
    key: "spark.airflow.execution_date"
    value: "2024-01-14"
  }
}
status {
  state: ERROR
  details: "Job failed with message [Exception in thread \"main\" org.apache.spark.sql.AnalysisException: Path does not exist: gs://data-lake-buck/raw/football_data/teams/2024-01-14.json]. Additional details can be found at:\nhttps://console.cloud.google.com/dataproc/jobs/a501dcd0-d8fb-4a94-a345-2017e7a8fe72?project=data-lake-project-409321&region=europe-west9\ngcloud dataproc jobs wait \'a501dcd0-d8fb-4a94-a345-2017e7a8fe72\' --region \'europe-west9\' --project \'data-lake-project-409321\'\nhttps://console.cloud.google.com/storage/browser/dataproc-staging-europe-west9-58760042001-uborul6i/google-cloud-dataproc-metainfo/13fc8c1e-24fd-4462-8a44-4c3a49636ea2/jobs/a501dcd0-d8fb-4a94-a345-2017e7a8fe72/\ngs://dataproc-staging-europe-west9-58760042001-uborul6i/google-cloud-dataproc-metainfo/13fc8c1e-24fd-4462-8a44-4c3a49636ea2/jobs/a501dcd0-d8fb-4a94-a345-2017e7a8fe72/driveroutput.*"
  state_start_time {
    seconds: 1706639585
    nanos: 868634000
  }
}
status_history {
  state: PENDING
  state_start_time {
    seconds: 1706639460
    nanos: 386118000
  }
}
status_history {
  state: SETUP_DONE
  state_start_time {
    seconds: 1706639460
    nanos: 439315000
  }
}
status_history {
  state: RUNNING
  state_start_time {
    seconds: 1706639460
    nanos: 681588000
  }
}
yarn_applications {
  name: "RawToFormatted"
  state: FINISHED
  progress: 1
  tracking_url: "http://cluster-f499-m.europe-west9-c.c.data-lake-project-409321.internal.:8088/proxy/application_1706622505355_0107/"
}
driver_output_resource_uri: "gs://dataproc-staging-europe-west9-58760042001-uborul6i/google-cloud-dataproc-metainfo/13fc8c1e-24fd-4462-8a44-4c3a49636ea2/jobs/a501dcd0-d8fb-4a94-a345-2017e7a8fe72/driveroutput"
driver_control_files_uri: "gs://dataproc-staging-europe-west9-58760042001-uborul6i/google-cloud-dataproc-metainfo/13fc8c1e-24fd-4462-8a44-4c3a49636ea2/jobs/a501dcd0-d8fb-4a94-a345-2017e7a8fe72/"
job_uuid: "a501dcd0-d8fb-4a94-a345-2017e7a8fe72"
done: true
; 74052)
[2024-01-30T18:33:11.431+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-30T18:33:11.450+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
