[2024-01-29T11:03:29.515+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: manage_data_lake_dag.spark_job_formatted manual__2024-01-29T11:03:17.058209+00:00 [queued]>
[2024-01-29T11:03:29.522+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: manage_data_lake_dag.spark_job_formatted manual__2024-01-29T11:03:17.058209+00:00 [queued]>
[2024-01-29T11:03:29.522+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-01-29T11:03:29.604+0000] {taskinstance.py:2191} INFO - Executing <Task(SparkSubmitOperator): spark_job_formatted> on 2024-01-29 11:03:17.058209+00:00
[2024-01-29T11:03:29.608+0000] {standard_task_runner.py:60} INFO - Started process 90673 to run task
[2024-01-29T11:03:29.614+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'manage_data_lake_dag', 'spark_job_formatted', 'manual__2024-01-29T11:03:17.058209+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/data_lake_dag.py', '--cfg-path', '/tmp/tmpe9kdwalj']
[2024-01-29T11:03:29.616+0000] {standard_task_runner.py:88} INFO - Job 98: Subtask spark_job_formatted
[2024-01-29T11:03:29.650+0000] {task_command.py:423} INFO - Running <TaskInstance: manage_data_lake_dag.spark_job_formatted manual__2024-01-29T11:03:17.058209+00:00 [running]> on host instance-1.europe-west9-a.c.data-lake-project-409321.internal
[2024-01-29T11:03:29.704+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='juniortemgoua0' AIRFLOW_CTX_DAG_ID='manage_data_lake_dag' AIRFLOW_CTX_TASK_ID='spark_job_formatted' AIRFLOW_CTX_EXECUTION_DATE='2024-01-29T11:03:17.058209+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-29T11:03:17.058209+00:00'
[2024-01-29T11:03:29.710+0000] {base.py:83} INFO - Using connection ID 'spark_default' for task execution.
[2024-01-29T11:03:29.712+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master  --conf spark.hadoop.yarn.resourcemanager.hostname= --conf spark.hadoop.yarn.resourcemanager.address=localhost:8032 --name arrow-spark --class RawToFormatted --queue root.default --deploy-mode client /home/juniortemgoua0/DataLake/jobs/processes/scala/spark_process/target/scala-2.12/spark_job_2.12-0.1.0.jar gs://data-lake-buck
[2024-01-29T11:03:31.984+0000] {spark_submit.py:571} INFO - Exception in thread "main" org.apache.spark.SparkException: Master must either be yarn or start with spark, mesos, k8s, or local
[2024-01-29T11:03:31.985+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.error(SparkSubmit.scala:1047)
[2024-01-29T11:03:31.985+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:256)
[2024-01-29T11:03:31.986+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:964)
[2024-01-29T11:03:31.986+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:194)
[2024-01-29T11:03:31.986+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:217)
[2024-01-29T11:03:31.986+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
[2024-01-29T11:03:31.986+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
[2024-01-29T11:03:31.986+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
[2024-01-29T11:03:31.986+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-01-29T11:03:32.012+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/juniortemgoua0/DataLake/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/juniortemgoua0/DataLake/venv/lib/python3.8/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self._application)
  File "/home/juniortemgoua0/DataLake/venv/lib/python3.8/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master  --conf spark.hadoop.yarn.resourcemanager.hostname= --conf spark.hadoop.yarn.resourcemanager.address=localhost:8032 --name arrow-spark --class RawToFormatted --queue root.default --deploy-mode client /home/juniortemgoua0/DataLake/jobs/processes/scala/spark_process/target/scala-2.12/spark_job_2.12-0.1.0.jar gs://data-lake-buck. Error code is: 1.
[2024-01-29T11:03:32.015+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=manage_data_lake_dag, task_id=spark_job_formatted, execution_date=20240129T110317, start_date=20240129T110329, end_date=20240129T110332
[2024-01-29T11:03:32.028+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 98 for task spark_job_formatted (Cannot execute: spark-submit --master  --conf spark.hadoop.yarn.resourcemanager.hostname= --conf spark.hadoop.yarn.resourcemanager.address=localhost:8032 --name arrow-spark --class RawToFormatted --queue root.default --deploy-mode client /home/juniortemgoua0/DataLake/jobs/processes/scala/spark_process/target/scala-2.12/spark_job_2.12-0.1.0.jar gs://data-lake-buck. Error code is: 1.; 90673)
[2024-01-29T11:03:32.074+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-29T11:03:32.087+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
