[2024-01-30T13:55:04.540+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: manage_data_lake_dag.dataproc_job_raw_to_formatted manual__2024-01-30T13:49:14.617694+00:00 [queued]>
[2024-01-30T13:55:04.547+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: manage_data_lake_dag.dataproc_job_raw_to_formatted manual__2024-01-30T13:49:14.617694+00:00 [queued]>
[2024-01-30T13:55:04.547+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 6
[2024-01-30T13:55:04.563+0000] {taskinstance.py:2191} INFO - Executing <Task(DataprocSubmitJobOperator): dataproc_job_raw_to_formatted> on 2024-01-30 13:49:14.617694+00:00
[2024-01-30T13:55:04.569+0000] {standard_task_runner.py:60} INFO - Started process 41360 to run task
[2024-01-30T13:55:04.576+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'manage_data_lake_dag', 'dataproc_job_raw_to_formatted', 'manual__2024-01-30T13:49:14.617694+00:00', '--job-id', '230', '--raw', '--subdir', 'DAGS_FOLDER/data_lake_dag.py', '--cfg-path', '/tmp/tmp9b8c9xqz']
[2024-01-30T13:55:04.580+0000] {standard_task_runner.py:88} INFO - Job 230: Subtask dataproc_job_raw_to_formatted
[2024-01-30T13:55:04.626+0000] {task_command.py:423} INFO - Running <TaskInstance: manage_data_lake_dag.dataproc_job_raw_to_formatted manual__2024-01-30T13:49:14.617694+00:00 [running]> on host instance-1.europe-west9-a.c.data-lake-project-409321.internal
[2024-01-30T13:55:04.701+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='juniortemgoua0' AIRFLOW_CTX_DAG_ID='manage_data_lake_dag' AIRFLOW_CTX_TASK_ID='dataproc_job_raw_to_formatted' AIRFLOW_CTX_EXECUTION_DATE='2024-01-30T13:49:14.617694+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-30T13:49:14.617694+00:00'
[2024-01-30T13:55:04.703+0000] {dataproc.py:2317} INFO - Submitting job
[2024-01-30T13:55:04.709+0000] {connection.py:234} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-30T13:55:04.714+0000] {base.py:83} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-01-30T13:55:04.912+0000] {dataproc.py:2329} INFO - Job e89962c0-f4a6-4f3b-a7cc-2b37cba2a450 submitted successfully.
[2024-01-30T13:55:04.925+0000] {dataproc.py:2363} INFO - Waiting for job e89962c0-f4a6-4f3b-a7cc-2b37cba2a450 to complete
[2024-01-30T13:55:45.247+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/juniortemgoua0/DataLake/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/juniortemgoua0/DataLake/venv/lib/python3.8/site-packages/airflow/providers/google/cloud/operators/dataproc.py", line 2364, in execute
    self.hook.wait_for_job(
  File "/home/juniortemgoua0/DataLake/venv/lib/python3.8/site-packages/airflow/providers/google/common/hooks/base_google.py", line 482, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/juniortemgoua0/DataLake/venv/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/dataproc.py", line 740, in wait_for_job
    raise AirflowException(f"Job failed:\n{job}")
airflow.exceptions.AirflowException: Job failed:
reference {
  project_id: "data-lake-project-409321"
  job_id: "e89962c0-f4a6-4f3b-a7cc-2b37cba2a450"
}
placement {
  cluster_name: "cluster-f499"
  cluster_uuid: "13fc8c1e-24fd-4462-8a44-4c3a49636ea2"
}
spark_job {
  main_class: "RawToFormatted"
  args: "gs://data-lake-buck"
  properties {
    key: "spark.airflow.execution_date"
    value: "2024-01-30"
  }
}
status {
  state: ERROR
  details: "Job failed with message [Error: Failed to load class RawToFormatted.]. Additional details can be found at:\nhttps://console.cloud.google.com/dataproc/jobs/e89962c0-f4a6-4f3b-a7cc-2b37cba2a450?project=data-lake-project-409321&region=europe-west9\ngcloud dataproc jobs wait \'e89962c0-f4a6-4f3b-a7cc-2b37cba2a450\' --region \'europe-west9\' --project \'data-lake-project-409321\'\nhttps://console.cloud.google.com/storage/browser/dataproc-staging-europe-west9-58760042001-uborul6i/google-cloud-dataproc-metainfo/13fc8c1e-24fd-4462-8a44-4c3a49636ea2/jobs/e89962c0-f4a6-4f3b-a7cc-2b37cba2a450/\ngs://dataproc-staging-europe-west9-58760042001-uborul6i/google-cloud-dataproc-metainfo/13fc8c1e-24fd-4462-8a44-4c3a49636ea2/jobs/e89962c0-f4a6-4f3b-a7cc-2b37cba2a450/driveroutput.*"
  state_start_time {
    seconds: 1706622939
    nanos: 216422000
  }
}
status_history {
  state: PENDING
  state_start_time {
    seconds: 1706622904
    nanos: 897451000
  }
}
status_history {
  state: SETUP_DONE
  state_start_time {
    seconds: 1706622904
    nanos: 952924000
  }
}
status_history {
  state: RUNNING
  state_start_time {
    seconds: 1706622905
    nanos: 244191000
  }
}
driver_output_resource_uri: "gs://dataproc-staging-europe-west9-58760042001-uborul6i/google-cloud-dataproc-metainfo/13fc8c1e-24fd-4462-8a44-4c3a49636ea2/jobs/e89962c0-f4a6-4f3b-a7cc-2b37cba2a450/driveroutput"
driver_control_files_uri: "gs://dataproc-staging-europe-west9-58760042001-uborul6i/google-cloud-dataproc-metainfo/13fc8c1e-24fd-4462-8a44-4c3a49636ea2/jobs/e89962c0-f4a6-4f3b-a7cc-2b37cba2a450/"
job_uuid: "e89962c0-f4a6-4f3b-a7cc-2b37cba2a450"
done: true

[2024-01-30T13:55:45.251+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=manage_data_lake_dag, task_id=dataproc_job_raw_to_formatted, execution_date=20240130T134914, start_date=20240130T135504, end_date=20240130T135545
[2024-01-30T13:55:45.265+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 230 for task dataproc_job_raw_to_formatted (Job failed:
reference {
  project_id: "data-lake-project-409321"
  job_id: "e89962c0-f4a6-4f3b-a7cc-2b37cba2a450"
}
placement {
  cluster_name: "cluster-f499"
  cluster_uuid: "13fc8c1e-24fd-4462-8a44-4c3a49636ea2"
}
spark_job {
  main_class: "RawToFormatted"
  args: "gs://data-lake-buck"
  properties {
    key: "spark.airflow.execution_date"
    value: "2024-01-30"
  }
}
status {
  state: ERROR
  details: "Job failed with message [Error: Failed to load class RawToFormatted.]. Additional details can be found at:\nhttps://console.cloud.google.com/dataproc/jobs/e89962c0-f4a6-4f3b-a7cc-2b37cba2a450?project=data-lake-project-409321&region=europe-west9\ngcloud dataproc jobs wait \'e89962c0-f4a6-4f3b-a7cc-2b37cba2a450\' --region \'europe-west9\' --project \'data-lake-project-409321\'\nhttps://console.cloud.google.com/storage/browser/dataproc-staging-europe-west9-58760042001-uborul6i/google-cloud-dataproc-metainfo/13fc8c1e-24fd-4462-8a44-4c3a49636ea2/jobs/e89962c0-f4a6-4f3b-a7cc-2b37cba2a450/\ngs://dataproc-staging-europe-west9-58760042001-uborul6i/google-cloud-dataproc-metainfo/13fc8c1e-24fd-4462-8a44-4c3a49636ea2/jobs/e89962c0-f4a6-4f3b-a7cc-2b37cba2a450/driveroutput.*"
  state_start_time {
    seconds: 1706622939
    nanos: 216422000
  }
}
status_history {
  state: PENDING
  state_start_time {
    seconds: 1706622904
    nanos: 897451000
  }
}
status_history {
  state: SETUP_DONE
  state_start_time {
    seconds: 1706622904
    nanos: 952924000
  }
}
status_history {
  state: RUNNING
  state_start_time {
    seconds: 1706622905
    nanos: 244191000
  }
}
driver_output_resource_uri: "gs://dataproc-staging-europe-west9-58760042001-uborul6i/google-cloud-dataproc-metainfo/13fc8c1e-24fd-4462-8a44-4c3a49636ea2/jobs/e89962c0-f4a6-4f3b-a7cc-2b37cba2a450/driveroutput"
driver_control_files_uri: "gs://dataproc-staging-europe-west9-58760042001-uborul6i/google-cloud-dataproc-metainfo/13fc8c1e-24fd-4462-8a44-4c3a49636ea2/jobs/e89962c0-f4a6-4f3b-a7cc-2b37cba2a450/"
job_uuid: "e89962c0-f4a6-4f3b-a7cc-2b37cba2a450"
done: true
; 41360)
[2024-01-30T13:55:45.288+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-30T13:55:45.299+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
