[2024-01-30T15:26:17.853+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: manage_data_lake_dag.dataproc_job_formatted_to_usage manual__2024-01-30T15:23:56.215289+00:00 [queued]>
[2024-01-30T15:26:17.860+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: manage_data_lake_dag.dataproc_job_formatted_to_usage manual__2024-01-30T15:23:56.215289+00:00 [queued]>
[2024-01-30T15:26:17.860+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-01-30T15:26:17.878+0000] {taskinstance.py:2191} INFO - Executing <Task(DataprocSubmitJobOperator): dataproc_job_formatted_to_usage> on 2024-01-30 15:23:56.215289+00:00
[2024-01-30T15:26:17.884+0000] {standard_task_runner.py:60} INFO - Started process 56840 to run task
[2024-01-30T15:26:17.891+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'manage_data_lake_dag', 'dataproc_job_formatted_to_usage', 'manual__2024-01-30T15:23:56.215289+00:00', '--job-id', '257', '--raw', '--subdir', 'DAGS_FOLDER/data_lake_dag.py', '--cfg-path', '/tmp/tmpjxaw813e']
[2024-01-30T15:26:17.894+0000] {standard_task_runner.py:88} INFO - Job 257: Subtask dataproc_job_formatted_to_usage
[2024-01-30T15:26:17.942+0000] {task_command.py:423} INFO - Running <TaskInstance: manage_data_lake_dag.dataproc_job_formatted_to_usage manual__2024-01-30T15:23:56.215289+00:00 [running]> on host instance-1.europe-west9-a.c.data-lake-project-409321.internal
[2024-01-30T15:26:18.014+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='juniortemgoua0' AIRFLOW_CTX_DAG_ID='manage_data_lake_dag' AIRFLOW_CTX_TASK_ID='dataproc_job_formatted_to_usage' AIRFLOW_CTX_EXECUTION_DATE='2024-01-30T15:23:56.215289+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-30T15:23:56.215289+00:00'
[2024-01-30T15:26:18.017+0000] {dataproc.py:2317} INFO - Submitting job
[2024-01-30T15:26:18.022+0000] {connection.py:234} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-30T15:26:18.027+0000] {base.py:83} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-01-30T15:26:18.221+0000] {dataproc.py:2329} INFO - Job 2808446d-1326-4c67-8eaa-90d17253e7f9 submitted successfully.
[2024-01-30T15:26:18.233+0000] {dataproc.py:2363} INFO - Waiting for job 2808446d-1326-4c67-8eaa-90d17253e7f9 to complete
[2024-01-30T15:27:58.967+0000] {dataproc.py:2367} INFO - Job 2808446d-1326-4c67-8eaa-90d17253e7f9 completed successfully.
[2024-01-30T15:27:58.983+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=manage_data_lake_dag, task_id=dataproc_job_formatted_to_usage, execution_date=20240130T152356, start_date=20240130T152617, end_date=20240130T152758
[2024-01-30T15:27:59.014+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-30T15:27:59.026+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
