[2024-01-31T08:36:10.256+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: manage_data_lake_dag.dataproc_job_raw_to_formatted manual__2024-01-31T08:35:28.153170+00:00 [queued]>
[2024-01-31T08:36:10.263+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: manage_data_lake_dag.dataproc_job_raw_to_formatted manual__2024-01-31T08:35:28.153170+00:00 [queued]>
[2024-01-31T08:36:10.264+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-01-31T08:36:10.278+0000] {taskinstance.py:2191} INFO - Executing <Task(DataprocSubmitJobOperator): dataproc_job_raw_to_formatted> on 2024-01-31 08:35:28.153170+00:00
[2024-01-31T08:36:10.284+0000] {standard_task_runner.py:60} INFO - Started process 146156 to run task
[2024-01-31T08:36:10.294+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'manage_data_lake_dag', 'dataproc_job_raw_to_formatted', 'manual__2024-01-31T08:35:28.153170+00:00', '--job-id', '468', '--raw', '--subdir', 'DAGS_FOLDER/data_lake_dag.py', '--cfg-path', '/tmp/tmp4gnzam2x']
[2024-01-31T08:36:10.298+0000] {standard_task_runner.py:88} INFO - Job 468: Subtask dataproc_job_raw_to_formatted
[2024-01-31T08:36:10.342+0000] {task_command.py:423} INFO - Running <TaskInstance: manage_data_lake_dag.dataproc_job_raw_to_formatted manual__2024-01-31T08:35:28.153170+00:00 [running]> on host instance-1.europe-west9-a.c.data-lake-project-409321.internal
[2024-01-31T08:36:10.415+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='juniortemgoua0' AIRFLOW_CTX_DAG_ID='manage_data_lake_dag' AIRFLOW_CTX_TASK_ID='dataproc_job_raw_to_formatted' AIRFLOW_CTX_EXECUTION_DATE='2024-01-31T08:35:28.153170+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-31T08:35:28.153170+00:00'
[2024-01-31T08:36:10.417+0000] {dataproc.py:2317} INFO - Submitting job
[2024-01-31T08:36:10.422+0000] {connection.py:234} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-31T08:36:10.427+0000] {base.py:83} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-01-31T08:36:10.662+0000] {dataproc.py:2329} INFO - Job 153d3712-6d19-420b-95a2-498120447f33 submitted successfully.
[2024-01-31T08:36:10.674+0000] {dataproc.py:2363} INFO - Waiting for job 153d3712-6d19-420b-95a2-498120447f33 to complete
[2024-01-31T08:38:31.740+0000] {dataproc.py:2367} INFO - Job 153d3712-6d19-420b-95a2-498120447f33 completed successfully.
[2024-01-31T08:38:31.756+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=manage_data_lake_dag, task_id=dataproc_job_raw_to_formatted, execution_date=20240131T083528, start_date=20240131T083610, end_date=20240131T083831
[2024-01-31T08:38:31.802+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-31T08:38:31.826+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
