[2024-01-30T16:03:21.690+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: manage_data_lake_dag.dataproc_job_formatted_to_usage manual__2024-01-30T15:43:30.488616+00:00 [queued]>
[2024-01-30T16:03:21.697+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: manage_data_lake_dag.dataproc_job_formatted_to_usage manual__2024-01-30T15:43:30.488616+00:00 [queued]>
[2024-01-30T16:03:21.698+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-01-30T16:03:21.714+0000] {taskinstance.py:2191} INFO - Executing <Task(DataprocSubmitJobOperator): dataproc_job_formatted_to_usage> on 2024-01-30 15:43:30.488616+00:00
[2024-01-30T16:03:21.719+0000] {standard_task_runner.py:60} INFO - Started process 62286 to run task
[2024-01-30T16:03:21.725+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'manage_data_lake_dag', 'dataproc_job_formatted_to_usage', 'manual__2024-01-30T15:43:30.488616+00:00', '--job-id', '258', '--raw', '--subdir', 'DAGS_FOLDER/data_lake_dag.py', '--cfg-path', '/tmp/tmps3ej_2rn']
[2024-01-30T16:03:21.728+0000] {standard_task_runner.py:88} INFO - Job 258: Subtask dataproc_job_formatted_to_usage
[2024-01-30T16:03:21.775+0000] {task_command.py:423} INFO - Running <TaskInstance: manage_data_lake_dag.dataproc_job_formatted_to_usage manual__2024-01-30T15:43:30.488616+00:00 [running]> on host instance-1.europe-west9-a.c.data-lake-project-409321.internal
[2024-01-30T16:03:21.845+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='juniortemgoua0' AIRFLOW_CTX_DAG_ID='manage_data_lake_dag' AIRFLOW_CTX_TASK_ID='dataproc_job_formatted_to_usage' AIRFLOW_CTX_EXECUTION_DATE='2024-01-30T15:43:30.488616+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-30T15:43:30.488616+00:00'
[2024-01-30T16:03:21.848+0000] {dataproc.py:2317} INFO - Submitting job
[2024-01-30T16:03:21.854+0000] {connection.py:234} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-30T16:03:21.859+0000] {base.py:83} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-01-30T16:03:22.032+0000] {dataproc.py:2329} INFO - Job ec60d7f3-8402-4e0a-b3b4-71ef86397199 submitted successfully.
[2024-01-30T16:03:22.044+0000] {dataproc.py:2363} INFO - Waiting for job ec60d7f3-8402-4e0a-b3b4-71ef86397199 to complete
[2024-01-30T16:05:12.884+0000] {dataproc.py:2367} INFO - Job ec60d7f3-8402-4e0a-b3b4-71ef86397199 completed successfully.
[2024-01-30T16:05:12.900+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=manage_data_lake_dag, task_id=dataproc_job_formatted_to_usage, execution_date=20240130T154330, start_date=20240130T160321, end_date=20240130T160512
[2024-01-30T16:05:12.931+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-30T16:05:12.943+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
